services:
  mojodocs-app:
    build: mojodocs_semantic_search
    environment:
      - DJANGO_SETTINGS_MODULE=mojodocs_semantic_search.settings_prod
    ports:
      - "8000:8000"
    restart: always
    mem_limit: "500m"
    cpus: 0.4
    depends_on:
     - chromadb
  
  chromadb:
    image: chromadb/chroma:0.4.22
    volumes:
      - ./chroma_db_only_manual:/chromadb/chromadb
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config chromadb/log_config.yml --timeout-keep-alive 30
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
    cpus: 0.3
    mem_limit: "300m"
    restart: always
