services:
  mojodocs-app:
    build: mojodocs_semantic_search
    command: "gunicorn mojodocs_semantic_search.wsgi:application --bind 0.0.0.0:8000 -w 2"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=mojodocs_semantic_search.settings_prod
    ports:
      - "8000:8000"
    restart: always
    mem_limit: "400m"
    cpus: 0.4
    depends_on:
     - chromadb
  
  chromadb:
    image: chromadb/chroma:0.4.22
    volumes:
      - ${CHROMADB_DIR:-./chroma_db}:/chroma/chroma
    command: uvicorn chromadb.app:app --reload --workers 2 --host 0.0.0.0 --port 8000 --log-config chromadb/log_config.yml --timeout-keep-alive 30
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    cpus: 0.4
    mem_limit: "400m"
    restart: always
